
stages:
  - test
  - build

php_codestyle:
  stage: test
  image: 1drop/php-70-docker-utils
  script:
  - php-cs-fixer fix -v --dry-run --using-cache=no

build:
  stage: build
  image: 1drop/php-70-docker-utils
  script:
  - composer install -ao --no-interaction --no-progress -d EightSelect
  - sed -i 's@__VERSION__@'"$CI_COMMIT_TAG"'@' EightSelect/plugin.xml
  artifacts:
    name: "EightSelect-v$CI_COMMIT_TAG"
    paths:
    - EightSelect
  only:
  - tags
